export const ONE_HOUR_IN_MILLISECONDS = 3_600_000;
export const ONE_DAY_IN_MILLISECONDS = ONE_HOUR_IN_MILLISECONDS * 24;
export const ONE_WEEK_IN_MILLISECONDS = ONE_DAY_IN_MILLISECONDS * 7;
export const THIFTEEN_MINUTES_IN_MILLISECONDS = ONE_HOUR_IN_MILLISECONDS / 4;
